version: '3.1'
services:
  web_ydace:
    image: odoo:15.0
    depends_on:
      - db
    ports:
      - "8069:8069"  
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./ydace/config:/etc/odoo
      - ./ydace/extra-addons:/mnt/extra-addons 
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
  web_cucharita_y_cucharon:
    image: odoo:15.0
    depends_on:
      - db
    ports:
      - "8070:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./cucharita_y_cucharon/config:/etc/odoo
      - ./cucharita_y_cucharon/extra-addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
  web_tasul:
    image: odoo:15.0
    depends_on:
      - db
    ports:
      - "8071:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./tasul/config:/etc/odoo
      - ./tasul/extra-addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
  db:
    container_name: db_odoo
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
volumes:
  odoo-web-data:
  odoo-db-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass
